config/routes.rb
Rails.application.routes.draw do
  get 'profiles/dashboard', to: 'profiles#dashboard'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :barbecues do
    resources :rentals, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end

  resources :rentals, only: [:show, :destroy, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/barbecue.rb
class Barbecue < ApplicationRecord
  validates :name, :description, :price, :location, presence: true
  validates :category, inclusion: { in: %w[Gaz Electrique Charbon Autre] }
  has_many :rentals, dependent: :destroy
  has_many :reviews, dependent: :destroy
  belongs_to :user
  mount_uploader :photo, PhotoUploader
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :barbecue
  belongs_to :user
  validates :start_date, :end_date, presence: true
  # validates_uniqueness_of :user_id, scope: :barbecue_id
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :barbecue
  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, numericality: { only_integer: true }
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  has_many :barbecues
  has_many :rentals

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/barbecues_controller.rb
class BarbecuesController < ApplicationController
  def index
    if params[:query].blank?
      @barbecues = Barbecue.all
    else
      @barbecues = Barbecue.where(location: params[:query].downcase.capitalize)
    end
    @barbecues_mapped = Barbecue.geocoded
    @markers = @barbecues_mapped.map do |barbecue|
      {
        lat: barbecue.latitude,
        lng: barbecue.longitude,
        infoWindow: render_to_string(partial: "shared/info_window", locals: { barbecue: barbecue }),
        image_url: helpers.asset_url('bbq.png')
      }
    end
  end

  def new
    @barbecue = Barbecue.new
  end

  def create
    @barbecue       = Barbecue.new(barbecue_params)
    @barbecue.user  = current_user
    if @barbecue.save
      redirect_to barbecue_path(@barbecue)
    else
      render :new
    end
  end

  def show
    @rental         = Rental.new
    @barbecue       = Barbecue.find(params[:id])
    @rentals        = @barbecue.rentals
    @dates_rentals  = @rentals.map do |rental|
      {
        from: rental.start_date,
        to: rental.end_date
      }
    end
  end

  def edit
    @barbecue = set_id
  end

  def update
    @barbecue = set_id
    @barbecue.update(barbecue_params)
    if @barbecue.save
      redirect_to barbecue_path(@barbecue)
    else
      render :edit
    end
  end

  def destroy
    @barbecue = set_id
    @barbecue.destroy
    redirect_to barbecues_path
  end

  private

  def barbecue_params
    params.require(:barbecue).permit(:name, :category, :description, :price, :location, :photo, :title)
  end

  def set_id
    Barbecue.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def dashboard
    @barbecues = current_user.barbecues
    @rentals = current_user.rentals
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  def new
    @barbecue = set_id_barbecue
    @rental = Rental.new
  end

  def create
    @rental = Rental.new(rental_params)
    @barbecue = set_id_barbecue
    @rental.barbecue = @barbecue
    @rental.user = current_user
    if @rental.save
      redirect_to rental_path(@rental)
    else
      redirect_to barbecue_path(@barbecue)
    end
  end

  def index
  end

  def show
    @rental = Rental.find(params[:id])
  end

  def destroy
  end

  private

  def rental_params
    params.require(:rental).permit(:start_date, :end_date, :barbecue_id)
  end

  def set_id_barbecue
    Barbecue.find(params[:barbecue_id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
  end

  def new
    @barbecue = Barbecue.find(params[:barbecue_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @barbecue = Barbecue.find(params[:barbecue_id])
    @review.barbecue = @barbecue
    if @review.save
      redirect_to barbecue_path(@barbecue)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def parse_date_fr(date)
    date.to_s.split("-").reverse.join("/")
  end
end

app/views/barbecues/_form.html.erb
  <div class="form-container">
  <%= simple_form_for(@barbecue) do |f| %>
   <div>
     <%= f.input :name, label:'Nom' %>
     <%= f.input :description %>
     <%= f.input :price, as: :integer, label: 'Prix de location' %>
     <%= f.input :location, label: 'Ville' %>
     <%= f.input :category, collection: ["Gaz", "Electrique", "Charbon", "Autre"], label:'Type de BBQ' %>
     <%= f.input :photo %>
     <%= f.input :photo_cache, as: :hidden %>
   </div>


   <%= f.submit 'Poster', class: "btn"%>

  <% end %>
</div>

app/views/barbecues/create.html.erb
<h1>Barbecues#create</h1>
<p>Find me in app/views/barbecues/create.html.erb</p>

app/views/barbecues/edit.html.erb
<div class="post-announce">
  <div class="registration-container">
    <h1>Je modifie mon annonce</h1>
    <%= render 'form', Barbecue: @barbecue  %>
  </div>
  <div class="gif-sub">
    <img alt="attente" src="https://tenor.com/view/grill-master-dancing-grilling-summer-bbq-gif-11706990.gif" />
  </div>
</div>

app/views/barbecues/index.html.erb
<div class="display-background">
  <div class="container">
    <h1 class ="display-title">
      <% if params[:query].present?  %>
        Barbecues disponibles sur <%= params[:query].downcase.capitalize %>
      <% end %>
    </h1>
    <div class="row">
      <% @barbecues.each do |barbecue| %>
        <div class="col-sm-12 col-md-4">
          <%= render "shared/card", barbecue: barbecue %>
        </div>
      <% end %>
    </div>
  </div>
  <div
    id="map"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="pk.eyJ1Ijoid2VybmRldiIsImEiOiJjazJnODkyNGowbjdnM2hwNXhpMzI1MmZ2In0.LPiWh1iQx0lgYsuk-B8QTg">
  </div>
</div>

app/views/barbecues/new.html.erb
<div class="post-announce">
  <div class="registration-container">
    <h1>Je poste mon annonce</h1>
    <%= render 'form', Barbecue: @barbecue  %>
  </div>
  <div class="gif-sub">
  <img alt="attente" src="https://tenor.com/view/grill-master-dancing-grilling-summer-bbq-gif-11706990.gif" />
  </div>
</div>

app/views/barbecues/show.html.erb
<div class="container-bbq-show">

  <div class="card-container">
    <div class="card-information">
      <div class="card-description">
        <h6> Type barbecue : <%= @barbecue.category %></h6>
        <h2> <%= @barbecue.name %> </h2>
        <p class="mail"> <%= @barbecue.user.email %> <p>
          <p class="descrition"> <%= @barbecue.description %> </p>
        </div>
        <div class="price-information">
          <div class="img-fa">
            <i class="far fa-money-bill-alt"></i>
          </div>
          <div class="card-price">
            <p class="gris">Prix à la journée</p>
            <p><em><%= @barbecue.price %>.00€</em></p>
          </div>
        </div>
        <div class="bbq-reviews">
          <% @barbecue.reviews.each do |review| %>
          <li>
            <strong>Note: </strong>
            <% review.rating.times do %>
            <i class="fas fa-star font-color-red"></i>
            <% end %>
            <% (5 - review.rating).times do %>
            <i class="far fa-star font-color-red"></i>
            <% end %>

          </li>
          <li class="bbq-text"><strong>Review: </strong><%= review.content%></li>
          <% end %>
        </div>
        <div class="card-rating">
        </div>
      </div>
      <div class="photo">
        <%= cl_image_tag @barbecue.photo ,height: 400, width: 350, class: "card-photo" %>
      </div>
    </div>

    <div class="booking-details">
      <% if @barbecue.user == current_user %>
      <%= link_to "Supprimer", @barbecue, class: "btn", method: :delete %>
      <%= link_to "Modifier", edit_barbecue_path(@barbecue), class: "btn" %>
      <% else %>
      <div id="rental-form" data-rentals="<%= @dates_rentals.to_json %>">
        <%= simple_form_for [@barbecue, @rental] do |f| %>
        <%= f.input  :start_date, as: :string, label: false, required: false, input_html: {id: "range_start", class: "d-none"} %>
        <%= f.input  :end_date,   as: :string, label: false, required: false, input_html: {id: "range_end" , class: "d-none"} %>
        <div id="new-rental-details">
          <div id="bbq-price">
            <p id="price" data-unitPrice="<%= @barbecue.price %>"> <%= @barbecue.price %> € </p>
            <div class="btn">
              <%= f.button :submit, "Je réserve" %>
            </div>
          </div>
        </div>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>BBQNB</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_pack_tag 'application' %>
<link href="https://fonts.googleapis.com/css?family=Rye&display=swap" rel="stylesheet">
 <link href="https://fonts.googleapis.com/css?family=Fugaz+One|Monda&display=swap" rel="stylesheet">
</head>
<body>
  <%= render 'shared/navbar' %>
  <%= render 'shared/flashes' %>
  <%= yield %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
  <%= render 'shared/footer' %>

</body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="home-container">
    <h1>Bienvenue sur BBQ<span class="text-color-red">&</span>B !</h1>
    <p>The place to Grill</p>
    <%= render 'shared/search_form' %>
  </div>
</div>

app/views/profiles/dashboard.html.erb
<h1 class="location">Mes locations</h1>

  <div class="container">
    <div class="row">
      <% @rentals.each do |rental| %>
        <div class="col-sm-12 col-md-4">
          <%= render "shared/card_rentals", rental: rental %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<h1 class="location">Mes annonces</h1>

  <div class="container">
    <div class="row">
      <% @barbecues.each do |barbecue| %>
        <div class="col-sm-12 col-md-4">
          <%= render "shared/card", barbecue: barbecue %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/rentals/create.html.erb
<h1>Rentals#create</h1>
<p>Find me in app/views/rentals/create.html.erb</p>

app/views/rentals/show.html.erb
<div class="container" >
  <h1 class="location">Félicitations !</h1>
  <p class="location">Votre reservation a bien été effectuée du <strong><%= parse_date_fr(@rental.start_date)%></strong> au <strong> <%= parse_date_fr(@rental.end_date)%></strong> pour un total de <strong> <%= ((@rental.end_date - @rental.start_date).to_i) * @rental.barbecue.price %> € </strong> </p>
<div class="container-bbq-show">
  <div class="container-card-bbq-details">
    <div class="card-bbq-show-name"><%= @rental.barbecue.name %> </div>
    <div class="card-bbq-show-details">

      <div class="card-bbq-show-photo">
        <%= cl_image_tag @rental.barbecue.photo, height: 320, width: 380, crop: :fill %>
      </div>
      <div class="card-bbq-show-information">
        <div class="card-bbq-show-text">
            <li class="bbq-text">Disponible à <strong><%= @rental.barbecue.location %></strong> </li>
            <li class="bbq-text">Utilisation: <strong><%= @rental.barbecue.category %></strong> </li>
            <li class="bbq-text"><strong>Description:</strong> <%= @rental.barbecue.description %> </li>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit, ut praesentium nulla obcaecati iusto rem consectetur sed tempore ad, adipisci ducimus? Debitis commodi, asperiores quos, nam eum enim architecto amet.</p>
        </div>
      </div>
    </div>
    <div class="bbq-reviews">
      <% @rental.barbecue.reviews.each do |review| %>
        <li><strong>Note: </strong><%= review.rating %></li>
        <li class="bbq-text"><strong>Review: </strong><%= review.content%></li>
      <% end %>
    </div>
  </div>
</div>
    <div class="btn1 mb-5">
      <%= link_to "Retour à mes annonces", profiles_dashboard_path, class: "btn" %>
    </div>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for [@barbecue, @review] do |f| %>
  <div>
 <%= f.input :content, label: 'Commentaire' %>
 <%= f.input :rating, collection: ["1", "2", "3", "4", "5"], label:'Note' %>
  </div>

  <%= f.submit 'Je valide', class: "btn"%>
<% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<div class="post-announce">
  <div class="registration-container">
    <h1>Nouvel avis</h1>
    <%= render 'form', Review: @review %>
     </div>
  <div class="gif-sub">
  <img alt="attente" src="https://media1.tenor.com/images/99cb5e50f6f45e351bbbe8ecc188f5b8/tenor.gif?itemid=14796831.gif" />
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner">
  <div class="home-container">
    <h1>Bienvenue sur BBQNB !</h1>
    <p>The place to Grill</p>
    <%= render 'shared/search_form' %>
  </div>
</div>

app/views/shared/_card.html.erb
<%= link_to barbecue_path(barbecue), class: "card-trip" do %>
  <div class="card-trip">
       <%= cl_image_tag barbecue.photo, height: 500, width: 450, crop: :fill %>
    <div class="card-trip-infos">
      <h2><%= barbecue.name %> </h2>
      <p> <%= barbecue.price  %> € </p>
    </div>
  </div>
<% end %>

app/views/shared/_card_rentals.html.erb
  <div class="card-trip car-trip-rental ">
       <%= cl_image_tag rental.barbecue.photo, height: 500, width: 450, crop: :fill %>
    <div class="card-trip-infos card-trip-infos-rental" id ="jolie">
      <strong><%=rental.barbecue.name%></strong>
      Du <%=parse_date_fr(rental.start_date)%> au <%=parse_date_fr(rental.end_date)%>
      </div>
             <div class="btn btn-avis">
            <%= link_to "Ajouter un avis", new_barbecue_review_path(rental.barbecue)%>
          </div>
  </div>

app/views/shared/_card_rented.html.erb
<%= link_to barbecue_path(barbecue), class: "card-trip" do %>
  <div class="card-trip">
       <%= cl_image_tag barbecue.photo, height: 500, width: 450, crop: :fill %>
    <div class="card-trip-infos">
      <h2><%= barbecue.name %> </h2>
      <p> <%= barbecue.price  %> €
    <i class="fas fa-trash"></i>
    </div>
  </div>
<% end %>

app/views/shared/_datepicker.html.erb
<div class="container">
  <div class="form-wrapper" style="width: 200px; margin: 0 auto;">
    <h2>Flatpickr Demo</h2>

    <%= simple_form_for :search, method: "get" do |f| %>
      <%= f.input :starts_at, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.input :ends_at, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.button :submit, "Go", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer-links">
    <a href="https://github.com/"><i class="fab fa-github"></i></a>
    <a href="https://www.instagram.com/?hl=fr"><i class="fab fa-instagram"></i></a>
    <a href="https://fr-fr.facebook.com/"><i class="fab fa-facebook"></i></a>
    <a href="https://twitter.com/?lang=fr"><i class="fab fa-twitter"></i></a>
    <a href="https://fr.linkedin.com/"><i class="fab fa-linkedin"></i></a>
  </div>
</footer>

app/views/shared/_info_window.html.erb
  <%= link_to barbecue_path(barbecue) do %>
<div id="info-window">
  <p><%= barbecue.name %></p>
  <p><%= barbecue.category %></p>
  <p><%= barbecue.price %>€ / j </p>
</div>
  <% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon d-flex justify-content-between sticky-top">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag("logo_transparent.png") %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Poster une annonce", new_barbecue_path, class: "nav-link mr-4 mt-1 btn" %>
        </li>
        <li class="nav-item dropdown mr-4">
          <%= image_tag "barbecue1.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Mes annonces", profiles_dashboard_path, class: "dropdown-item" %>
            <%= link_to "Grill out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item d-flex mr-4 px-2">
          <%= link_to "Poster une annonce", new_barbecue_path, class: "nav-link mr-4 btn" %>
          <%= link_to "Grill-up", new_user_registration_path, class: "nav-link mr-4 btn" %>
          <%= link_to "Grill-in", new_user_session_path, class: "nav-link btn" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_new-card.html.erb
<div class="card-container">
  <div class="card-information">
    <div class="card-description">
      <h6> Type barbecue :</h6>
      <h2> WEBER </h2>
      <p class="mail"> mickael.verdin@numericable.fr <p>
        <p class="descrition"> Lorem ipsum dolor sit amet, consectetur adipisicing elit.
          Quisquam quas quis dolores ad debitis ex corrupti impedit, reiciendis dignissimos
        mollitia laborum eius quidem voluptatibus quo omnis tempora odio expedita. Atque! </p>
      </div>
      <div class="date-information">
        <div class="img-fa">
        <i class="fas fa-calendar-alt"></i>
        </div>
        <div class="card-date">
          <p class="gris">Disponible à partir du : </p>
          <p><em> La dispo</em> </p>
        </div>
      </div>
      <div class="price-information">
        <div class="img-fa">
        <i class="far fa-money-bill-alt"></i>
         </div>
        <div class="card-price">
          <p class="gris">Prix à la journée</p>
          <p><em><%= @barbecue.price %></em></p>
        </div>
      </div>
    </div>
    <div class="photo">
      <%= cl_image_tag "http://gallery.tranchesdunet.com/barbecue-originaux/barbecue_06-plateau-design-630x510.jpg" ,height: 700, width: 800, class: "card-photo" %>
    </div>
  </div>
</div>

app/views/shared/_search_form.html.erb
<%= simple_form_for :search, url: barbecues_path, method: :get do |f| %>
  <div class="search-form-control form-group">
    <input class="form-control string required" type="text" name="query" id="search_query" placeholder="Quelle est votre ville ?" />
    <button name="button" type="submit" class="btn btn-flat">
      <i class="fas fa-search"></i> Griller
    </button>
  </div>
<% end %>